def writeletter(self, letter, color):
    if letter == 'A':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([7, 6], color)
        self.ledmatrix.ledon([7, 5], color)
        self.ledmatrix.ledon([7, 4], color)
        self.ledmatrix.ledon([7, 3], color)
        self.ledmatrix.ledon([7, 2], color)
        self.ledmatrix.ledon([4, 4], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([6, 4], color)

    if letter == 'C':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([6, 2], color)
        self.ledmatrix.ledon([7, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([7, 7], color)

    elif letter == 'E':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([7, 7], color)
        self.ledmatrix.ledon([4, 5], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([6, 5], color)
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([6, 2], color)
        self.ledmatrix.ledon([7, 2], color)

    elif letter == 'G':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([7, 7], color)
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([6, 2], color)
        self.ledmatrix.ledon([7, 2], color)
        self.ledmatrix.ledon([7, 3], color)
        self.ledmatrix.ledon([7, 4], color)
        self.ledmatrix.ledon([6, 4], color)
        self.ledmatrix.ledon([5, 4], color)

    elif letter == 'I':
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([5, 3], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([5, 6], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([6, 2], color)

    elif letter == 'K':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 5], color)
        self.ledmatrix.ledon([5, 6], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([6, 3], color)
        self.ledmatrix.ledon([6, 2], color)

    elif letter == 'M':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 6], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([7, 7], color)
        self.ledmatrix.ledon([7, 6], color)
        self.ledmatrix.ledon([7, 5], color)
        self.ledmatrix.ledon([7, 4], color)
        self.ledmatrix.ledon([7, 3], color)
        self.ledmatrix.ledon([7, 2], color)

    elif letter == 'N':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 6], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([6, 4], color)
        self.ledmatrix.ledon([7, 7], color)
        self.ledmatrix.ledon([7, 6], color)
        self.ledmatrix.ledon([7, 5], color)
        self.ledmatrix.ledon([7, 4], color)
        self.ledmatrix.ledon([7, 3], color)
        self.ledmatrix.ledon([7, 2], color)

    elif letter == 'O':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([7, 7], color)
        self.ledmatrix.ledon([7, 6], color)
        self.ledmatrix.ledon([7, 5], color)
        self.ledmatrix.ledon([7, 4], color)
        self.ledmatrix.ledon([7, 3], color)
        self.ledmatrix.ledon([7, 2], color)
        self.ledmatrix.ledon([6, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([4, 2], color)

    elif letter == 'V':
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([4, 3], color)
        self.ledmatrix.ledon([6, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([7, 4], color)
        self.ledmatrix.ledon([7, 5], color)
        self.ledmatrix.ledon([7, 6], color)
        self.ledmatrix.ledon([7, 7], color)

    elif letter == 'R':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([7, 6], color)
        self.ledmatrix.ledon([7, 5], color)
        self.ledmatrix.ledon([6, 4], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([4, 4], color)
        self.ledmatrix.ledon([7, 3], color)
        self.ledmatrix.ledon([7, 2], color)

    elif letter == 'S':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([6, 2], color)
        self.ledmatrix.ledon([7, 2], color)
        self.ledmatrix.ledon([7, 3], color)
        self.ledmatrix.ledon([7, 4], color)
        self.ledmatrix.ledon([7, 5], color)
        self.ledmatrix.ledon([6, 5], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([4, 5], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([7, 7], color)

    elif letter == 'T':
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([5, 3], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([5, 6], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([7, 7], color)

    elif letter == 'Y':
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([5, 3], color)
        self.ledmatrix.ledon([4, 4], color)
        self.ledmatrix.ledon([6, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([7, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([7, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([7, 7], color)

    elif letter == '1':
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([6, 2], color)
        self.ledmatrix.ledon([5, 3], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([5, 6], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([3, 6], color)

    elif letter == '2':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([6, 2], color)
        self.ledmatrix.ledon([4, 3], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([6, 5], color)
        self.ledmatrix.ledon([6, 6], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([3, 6], color)

    elif letter == '3':
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([6, 3], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([6, 6], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([3, 6], color)

    elif letter == '4':
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([5, 3], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([5, 6], color)
        self.ledmatrix.ledon([6, 4], color)
        self.ledmatrix.ledon([4, 4], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)

    elif letter == '5':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([6, 3], color)
        self.ledmatrix.ledon([5, 4], color)
        self.ledmatrix.ledon([4, 5], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([6, 7], color)

    elif letter == '6':
        self.ledmatrix.ledon([4, 2], color)
        self.ledmatrix.ledon([5, 2], color)
        self.ledmatrix.ledon([6, 3], color)
        self.ledmatrix.ledon([6, 4], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([4, 5], color)
        self.ledmatrix.ledon([3, 5], color)
        self.ledmatrix.ledon([3, 4], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([3, 6], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([6, 7], color)

    elif letter == '7':
        self.ledmatrix.ledon([3, 2], color)
        self.ledmatrix.ledon([3, 3], color)
        self.ledmatrix.ledon([4, 4], color)
        self.ledmatrix.ledon([5, 5], color)
        self.ledmatrix.ledon([6, 6], color)
        self.ledmatrix.ledon([6, 7], color)
        self.ledmatrix.ledon([5, 7], color)
        self.ledmatrix.ledon([4, 7], color)
        self.ledmatrix.ledon([3, 7], color)
        self.ledmatrix.ledon([3, 6], color)

    time.sleep(0.5)
    self.ledmatrix.matrixclear()
